Repository GazePlay/GazePlay, pull requests merged in 2021-09, with the labels that each got.

#1483 Removing the events when we chose the wrong target or when all the go…
  gazeplay-games/src/main/java/net/gazeplay/games/order/Order.java
  gazeplay-games/src/main/java/net/gazeplay/games/order/Target.java
Labels: fix before release

#1492 Stoping all media at the end of the game
  gazeplay-games/src/main/java/net/gazeplay/games/videogrid/VideoGrid.java
Labels: fix before release

#1480 fix the bug in the cake game
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java
Labels: check if fixed

#1477 Fixing custom dialog for colors #1472 and #1243
  gazeplay-games-commons/src/main/java/net/gazeplay/components/GazeFollowerIndicator.java
  gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorBox.java
  gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorToolBox.java
  gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java
  gazeplay-games/src/main/java/net/gazeplay/games/colors/CustomColorBox.java
  gazeplay-games/src/main/java/net/gazeplay/games/colors/CustomColorPicker.java
Labels: check if fixed, fix before release

#1462 Fixing loading screen not being closed
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuController.java
Labels: fix before release
