Repository GazePlay/GazePlay, pull requests merged in 2021-07, with the labels that each got.

#1354 Mouse event triggered at game launch #1339
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
  gazeplay-games-commons/src/main/java/net/gazeplay/IGameContext.java
  gazeplay-games/src/main/java/net/gazeplay/games/blocs/Blocs.java
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java
  gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java
  gazeplay-games/src/main/java/net/gazeplay/games/cups/Cup.java
  gazeplay-games/src/main/java/net/gazeplay/games/cups/CupsAndBalls.java
  gazeplay-games/src/main/java/net/gazeplay/games/literacy/Bloc.java
  gazeplay-games/src/main/java/net/gazeplay/games/literacy/Letters.java
  gazeplay-games/src/main/java/net/gazeplay/games/magiccards/Card.java
  gazeplay-games/src/main/java/net/gazeplay/games/magiccards/MagicCards.java
  gazeplay-games/src/main/java/net/gazeplay/games/math101/Card.java
  gazeplay-games/src/main/java/net/gazeplay/games/math101/Math101.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/Memory.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryCard.java
  gazeplay-games/src/main/java/net/gazeplay/games/slidingpuzzle/SlidingPuzzle.java
  gazeplay-games/src/main/java/net/gazeplay/games/slidingpuzzle/SlidingPuzzleCard.java
  gazeplay-games/src/main/java/net/gazeplay/games/whereisit/PictureCard.java
  gazeplay-games/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
Labels: change needed

#1366 Oui non
  gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
  gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGame.java
  gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGameSpecSource.java
  gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGameVariant.java
  gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGameVariantGenerator.java
  gazeplay-games/src/main/resources/data/opinions/thumbs/correct2.png
  gazeplay-games/src/main/resources/data/opinions/thumbs/error.png
Labels: change needed

#1374 Bulle taille explosion
  gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
  gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameVariantGenerator.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Bubble.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/BubblesGameVariant.java
Labels: change needed

#1316 Cake factory easy level
  gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeGameVariant.java
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/ScreenCake.java
  gazeplay-games/src/main/resources/data/multilinguism/multilinguism.csv
Labels: change needed

#1375 Remove the duration of the fixation in games that do not use the fixation #1368
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
  gazeplay-games-commons/src/main/java/net/gazeplay/IGameContext.java
  gazeplay-games/src/main/java/net/gazeplay/games/biboulejump/BibouleJump.java
  gazeplay-games/src/main/java/net/gazeplay/games/blocs/Blocs.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Bubble.java
  gazeplay-games/src/main/java/net/gazeplay/games/creampie/CreamPie.java
  gazeplay-games/src/main/java/net/gazeplay/games/divisor/Divisor.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/Moles.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/Ninja.java
  gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Piano.java
  gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
  gazeplay-games/src/main/java/net/gazeplay/games/room/Room.java
  gazeplay-games/src/main/java/net/gazeplay/games/shooter/Shooter.java
  gazeplay-games/src/main/java/net/gazeplay/games/space/SpaceGame.java
Labels: change needed

#1353 we can lose in the game FrogRace now
  gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
Labels: change needed

#1321 Stop recording bbb pressed
  gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java
Labels: change needed

#1336 Increase elements size
  gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java
  gazeplay-core/src/main/java/net/gazeplay/ui/AnimationSpeedRatioControl.java
  gazeplay-core/src/main/java/net/gazeplay/ui/ElementSizeControl.java
  gazeplay-core/src/main/java/net/gazeplay/ui/FixationLengthControl.java
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
  gazeplay-games/src/main/java/net/gazeplay/games/creampie/CreamPie.java
  gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/Ninja.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/Target.java
Labels: change needed

#1378 New game whack a mole with user's portraits #531
  gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
  gazeplay-games/src/main/java/net/gazeplay/games/moles/Moles.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesChar.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesGameVariant.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesGameVariantGenerator.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/WhacAMoleGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/WhacAMoleGameSpecSource.java
Labels: change needed, invalid

#1333 Dwell time fixation zero duration
  gazeplay-core/src/main/java/net/gazeplay/GazePlay.java
  gazeplay-core/src/main/java/net/gazeplay/ui/FixationLengthControl.java
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
  gazeplay-games-commons/src/main/java/net/gazeplay/components/ProgressPortrait.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Bubble.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/ColoredBubblesGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/PortraitBubblesGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Target.java
  gazeplay-games/src/main/java/net/gazeplay/games/creampie/CreampieGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/creampie/Hand.java
  gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/Moles.java
  gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesChar.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/NinjaGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/Target.java
  gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Piano.java
  gazeplay-games/src/main/java/net/gazeplay/games/pianosight/PianoGameLauncher.java
Labels: change needed, fix before release

#1384 Fixed pr for Dynamic Memory and Ninja games
  gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java
  gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameVariantDialog.java
  gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
  gazeplay-games/src/main/java/net/gazeplay/games/memory/Memory.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryCard.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryGameVariantGenerator.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryLettersGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryNumbersGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/OpenMemoryGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/OpenMemoryLettersGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/memory/OpenMemoryNumbersGameLauncher.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/Ninja.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/NinjaGameVariant.java
  gazeplay-games/src/main/java/net/gazeplay/games/ninja/Target.java
  gazeplay-games/src/test/java/net/gazeplay/games/memory/MemoryTest.java
Labels: fix before release

#1405 Disapearing fix about automatic next layer in cakes fixed
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java
  gazeplay-games/src/main/java/net/gazeplay/games/cakes/ScreenCake.java
Labels: fix before release

#1400 Translations to Russian and Belarusian
  gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/CustomLocale.java
  gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/Languages.java
  gazeplay-commons/src/test/java/net/gazeplay/commons/utils/multilinguism/LanguagesTest.java
  gazeplay-core/src/main/resources/data/common/flags/800px-Flag_of_Belarus.svg.png
  gazeplay-core/src/main/resources/data/common/flags/800px-Flag_of_India.svg.png
  gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
  gazeplay-core/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextTest.java
Labels: fix before release
